#!/bin/bash

#
# git-repo - DevOpsBroker Bash completion script for the git-repo utility
#
# Copyright (C) 2019 Edward Smith <edwardsmith@devopsbroker.org>
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program.  If not, see <http://www.gnu.org/licenses/>.
#
# -----------------------------------------------------------------------------
# Developed on Ubuntu 18.04.1 LTS running kernel.osrelease = 4.15.0-45
#
# -----------------------------------------------------------------------------
#

function _git-repo() {

	COMPREPLY=()

	local commandOption=${COMP_WORDS[1]}
	local currentWord=${COMP_WORDS[COMP_CWORD]}

	# Check if we need to exit when we have already completed the git-repo command option
	if [ $COMP_CWORD -ge 2 ]; then
		if [ $commandOption == "discard" ]; then
			COMPREPLY+=($(/bin/ls ${currentWord}*))
		fi

		return
	fi

	local commands="amend config create-branch delete-branch diff discard history list-branches list-commits list-config list-tags release restore stat test-ssh update"

	COMPREPLY=( $(compgen -W "${commands}" -- ${currentWord}) )
	return 0
}

complete -F _git-repo git-repo
