#!/bin/bash

#
# bindmount - DevOpsBroker utility for creating bind mounts
#
# Copyright (C) 2019 Edward Smith <edwardsmith@devopsbroker.org>
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program.  If not, see <http://www.gnu.org/licenses/>.
#
# -----------------------------------------------------------------------------
# Developed on Ubuntu 18.04.2 LTS running kernel.osrelease = 4.18.0-15
#
# This utility does the following tasks:
#   o Moves data from the source directory to the destination directory
#     - Confirmation is made to delete any data in the destination
#   o Adds a bind mount entry from destination directory to source directory in /etc/fstab
#   o Performs the actual bind mount between destination and source
# -----------------------------------------------------------------------------
#

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Preprocessing ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Load /etc/devops/ansi.conf if ANSI_CONFIG is unset
if [ -z "$ANSI_CONFIG" ] && [ -f /etc/devops/ansi.conf ]; then
	source /etc/devops/ansi.conf
fi

${ANSI_CONFIG?"[1;91mCannot load '/etc/devops/ansi.conf': No such file[0m"}

# Load /etc/devops/exec.conf if EXEC_CONFIG is unset
if [ -z "$EXEC_CONFIG" ] && [ -f /etc/devops/exec.conf ]; then
	source /etc/devops/exec.conf
fi

${EXEC_CONFIG?"[1;91mCannot load '/etc/devops/exec.conf': No such file[0m"}

# Load /etc/devops/functions.conf if FUNC_CONFIG is unset
if [ -z "$FUNC_CONFIG" ] && [ -f /etc/devops/functions.conf ]; then
	source /etc/devops/functions.conf
fi

${FUNC_CONFIG?"[1;91mCannot load '/etc/devops/functions.conf': No such file[0m"}

# Load /etc/devops/functions-io.conf if FUNC_IO_CONFIG is unset
if [ -z "$FUNC_IO_CONFIG" ] && [ -f /etc/devops/functions-io.conf ]; then
	source /etc/devops/functions-io.conf
fi

${FUNC_IO_CONFIG?"[1;91mCannot load '/etc/devops/functions-io.conf': No such file[0m"}

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Robustness ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

set -o errexit                 # Exit if any statement returns a non-true value
set -o nounset                 # Exit if use an uninitialised variable
set -o pipefail                # Exit if any statement in a pipeline returns a non-true value
IFS=$'\n\t'                    # Default the Internal Field Separator to newline and tab

scriptName='bindmount'

# Display error if not running as root
if [ "$USER" != 'root' ]; then
	printError $scriptName 'Permission denied (you must be root)'
	exit 1
fi

################################## Variables ##################################

## Options
SOURCE_DIR=${1:-}
DEST_DIR=${2:-}

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ OPTION Parsing ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

errorMessage=$(isValidDirectory $scriptName "$SOURCE_DIR")

# Display error if source directory parameter is missing or invalid
if [ "$errorMessage" != '0' ]; then
	echo "$errorMessage"
	echo
	printUsage "$scriptName SOURCE_DIR DEST_DIR"

	exit 1
fi

errorMessage=$(isValidDirectory $scriptName "$DEST_DIR")

# Display error if destination directory parameter is missing or invalid
if [ "$errorMessage" != '0' ]; then
	echo "$errorMessage"
	echo
	printUsage "$scriptName $SOURCE_DIR DEST_DIR"

	exit 1
fi

# Load all bind mounts from /etc/fstab
mapfile -t bindMountList < <($EXEC_GREP -E '\bbind\b' /etc/fstab)

# Display message if source dirctory has already been moved
for bindMount in "${bindMountList[@]}"; do
	if [[ "$bindMount" =~ [[:blank:]]$SOURCE_DIR[[:blank:]] ]]; then
		printInfo "Source directory '$SOURCE_DIR' has already been bind mounted"
		printInfo 'Exiting'
		exit 0
	fi
done

################################### Actions ###################################

# Check the status of the destination directory if the source directory is not empty
if [ "$($EXEC_LS -A $SOURCE_DIR)" ]; then

	if [ "$($EXEC_LS -A $DEST_DIR)" ]; then
		echo "${bold}${yellow}Destination directory '${green}$DEST_DIR${yellow}' is not empty"
		echo "Are you sure you want to delete all of its contents?${white}"
		select confirmDelete in 'Yes' 'No'; do
			if [ "$confirmDelete" == 'Yes' ]; then
				echo
				printInfo "Cleaning $DEST_DIR directory"
				$EXEC_RM -rf "$DEST_DIR/*"
			else
				echo
				printInfo "Exiting"
				exit 0
			fi
			break;
		done
	fi

	printInfo "Moving $SOURCE_DIR directory to $DEST_DIR"
	$EXEC_CP -a "$SOURCE_DIR" "$DEST_DIR"
	$EXEC_RM -rf "$SOURCE_DIR/*"
fi

# Backup existing /etc/fstab
printInfo 'Backing up /etc/fstab'
$EXEC_CP -a /etc/fstab /etc/fstab.bak

# Add bind mounts comment to /etc/fstab if necessary
if [ "${#bindMountList[@]}" -eq 0 ]; then
	# The -e flag tells echo to interpret the newline character
	echo -e '\n# Bind mounts' >> /etc/fstab
fi

printInfo "Adding $DEST_DIR bind mount to /etc/fstab"
echo "$DEST_DIR	$SOURCE_DIR	none	bind	0	0" >> /etc/fstab

printInfo "Bind mounting $DEST_DIR directory to $SOURCE_DIR"
$EXEC_MOUNT --bind "$DEST_DIR" "$SOURCE_DIR"

exit 0
